### ISSUE TITLE
Gradle migration

### ISSUE THREAD

**Issue by bolobobo** [linkedin/parseq#178]
Currently, ParSeq is not quite friendly for contributors, because it involves so many heterogeneous build frameworks for its components. For example, Ant for main parseq module, Makefile for tracevis, Maven for contrib components. 

- [ ] separate tools/tracevis from current project #179 
- [ ] convert contrib maven project to gradle #180 
- [ ] convert main module ant building to gradle #181 
- [ ] delete useless scripts and docs
